dist: xenial
language: bash
services: docker
matrix:
  include:
    - name: x86_64-linux
    - name: aarch64-linux
      script: make qemu test
  fast_finish: true
before_script:
  # Show environment.
  - uname -a
  - id
  - pwd
script:
  - tests/sample_test.sh
