# https://hub.docker.com/r/multiarch/ubuntu-debootstrap/tags/
FROM multiarch/ubuntu-debootstrap:arm64-bionic

ARG INSTALL_DEPS=0

# Test with non-root user.
ENV TEST_USER gogut
ENV WORK_DIR "/build"
ENV PATH "/usr/local/bin:${PATH}"

RUN uname -a

# Create test user and the environment
RUN useradd -m "${TEST_USER}"
WORKDIR "${WORK_DIR}"
COPY . .
RUN chown -R "${TEST_USER}:${TEST_USER}" "${WORK_DIR}"

ENV PATH "${WORK_DIR}/scripts:${PATH}"

# Enable sudo without password for convenience.
# RUN echo "${TEST_USER} ALL = NOPASSWD: ALL" >> /etc/sudoers

RUN scripts/install-deps.sh

CMD bash
