FROM quay.io/gogut/yamp:arm64

# Create non-root user
RUN useradd -m gogut

USER gogut
WORKDIR /home/gogut
COPY scripts/gogut_bashrc .bashrc

# Install initial apps for nextflow
RUN nextflow -version

CMD ["bash"]
